### ISSUE TITLE
wp rocket regenerate not working properly

### ISSUE THREAD

**Issue by sergeyarl** [wp-media/wp-rocket-cli#15]
Hi! 

We have two exception URLs that should be excluded from caching. They are: 

`/url1/`
`/url/2/`

When we configure them via WP web admin interface (**Never cache the following pages** option) , everything goes ok, and all the pages are cached except for these two. However, when we run 

`$ wp rocket regenerate --file=config `

In this case ALL the pages seem to get excluded from caching except for home page. 

We investigated further and found that the configs have one difference:

the working one (generated via web UI ) has the following block:

```
$rocket_cache_query_strings = array (
  0 => 'q',
);

```

and the 'faulty' one (generated via wp-cli tool) has a bit different block:

```
$rocket_cache_query_strings = array (
);

```
When we manually add  missing `0 => 'q',` everything starts to work properly. 

The complete working config looks like this:

```

<?php
defined( 'ABSPATH' ) or die( 'Cheatin\' uh?' );

$rocket_cookie_hash = '1212123123123';
$rocket_secret_cache_key = '123123123123123123123';
$rocket_cache_mobile = '1';
$rocket_cache_ssl = '1';
$rocket_cache_reject_uri = '/url1/|/url/2/|/bla_bla_bla/|.*/feed/?|/wp-json/(.*)';
$rocket_cache_reject_cookies = 'wordpress_logged_in_|wp-postpass_|wptouch_switch_toggle|comment_author_|comment_author_email_';
$rocket_cache_query_strings = array (
  0 => 'q',
);
$rocket_cache_reject_ua = 'facebookexternalhit';
$rocket_cache_mandatory_cookies = '';
$rocket_cache_dynamic_cookies = array (
);

```
Can you please check if it is a bug, or probably we're doing something wrong ?

Thank you! 

Regards,
Sergey

**Comment by iCaspar** [comment]
✅ Can Reproduce.

✅ Root cause:
This is to do with running on nginx.
We add a filter to the `rocket_cache_query_strings` hook [here](https://github.com/wp-media/wp-rocket/blob/master/inc/3rd-party/hosting/nginx.php).
That filter does not get added when running via cli, so we lose the compatibility when generating the config.
The filter depends on the wp global `$is_nginx` being set -- which globals are not by default when running wp-cli.

✅ Scope a solution:
1. Add a parameter that can indicate we need to set the `$is_nginx` global before running the process.
2. Check for the parameter and set the global when true.

✅ Effort = [XS]
